### PR TITLE
[WS-79] - [MinorVersion] - Addressed Reza's comments on WS-79

### PR DESCRIPTION
**Pull request by metacoding**
- Fixed the tests (both ng e2e and ng tests)
- Updated the document
- Fixed a few other minor problems

### CODE REVIEW

**Comment by reza-esfandyari** [comment]
Finished the review. 
1. e2e test is still failing on my machine (I had a clean installation)
2. projects seems to have an issue on Linux machine. I could not install it (npm install failed)
3. I could not find any doc on how to use ng test (Karma debugger nor e2e). I think everyone needs to know how to modify and use this in order to avoid build failure later on

**Comment by metacoding** [comment]
@reza-esfandyari  Thanks for your review but I spent a long time and did not find any issue
1- for running e2e tests please run ng server and then run ng e2e. It is designed for remote testing that is why it doesn't start the app itself
2- I got my branch on Linux and ran it. Had no issue at all. Better to check my document about Linux preparation in old project Worksignal https://github.com/metacoding/Worksignal/wiki/Setup-on-Linux-Ubuntu
I think the problem you see is happening because Webpack has some native plugins and needed to compile them. On linux you need build-essential to be installed.

Reference-style: 
alt text

3- Karma has its own website. Everyone needs to learn about Jasmine, Karma and Protractor from their official websites.

**Comment by reza-esfandyari** [comment]
ws-79: :shipit: looks good to me. thanks

**Comment by metacoding** [comment]
Thanks Reza jan, but I cannot merge until you set your review to approved :)

**Pull request merged**
